KUBERNETES_COLLECTION = "kubernetes_docs"
EMBEDDING_MODEL = "nomic-embed-text"

EMBEDDING_DIMENSION = 768
METRIC_TYPE = "COSINE"
MAX_CONTENT_LENGTH = 10000
MAX_SOURCE_LENGTH = 1000
MAX_FILENAME_LENGTH = 500
MAX_HEADING_LENGTH = 1000
MAX_HEADING_PATH_LENGTH = 2000